"""Article export functionality for backup"""
import os
import sys
import sqlite3
from datetime import datetime
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from models import get_db_connection

def export_all_posts_to_markdown(output_dir='exports'):
    """Export all posts to individual markdown files"""
    # Create exports directory
    export_path = Path(output_dir)
    export_path.mkdir(exist_ok=True)
    
    # Create subdirectories
    posts_dir = export_path / 'posts'
    posts_dir.mkdir(exist_ok=True)
    
    images_dir = export_path / 'images'
    images_dir.mkdir(exist_ok=True)
    
    conn = get_db_connection()
    cursor = conn.cursor()
    
    # Get all posts with their metadata
    cursor.execute('''
        SELECT 
            p.id, p.title, p.content, p.created_at, p.updated_at, p.is_published,
            c.name as category_name,
            GROUP_CONCAT(t.name, ',') as tags
        FROM posts p
        LEFT JOIN categories c ON p.category_id = c.id
        LEFT JOIN post_tags pt ON p.id = pt.post_id
        LEFT JOIN tags t ON pt.tag_id = t.id
        GROUP BY p.id
        ORDER BY p.created_at DESC
    ''')

    posts = [dict(row) for row in cursor.fetchall()]

    exported_count = 0
    for post in posts:
        # Create markdown content
        markdown = f"""---
title: {post['title']}
date: {post['created_at']}
updated: {post.get('updated_at', post['created_at'])}
published: {bool(post['is_published'])}
category: {post['category_name'] or 'Uncategorized'}
tags: [{post['tags'] or ''}]
type: post
---

# {post['title']}

{post['content']}
"""
        
        # Safe filename
        safe_title = "".join(c for c in post['title'] if c.isalnum() or c in (' ', '-', '_')).strip()
        filename = f"{post['id']}_{safe_title[:50]}.md"
        
        # Write to file
        file_path = posts_dir / filename
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(markdown)
        
        exported_count += 1
    
    conn.close()
    
    # Create README for export
    readme_content = f"""# Blog Export

Export Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

Total Posts: {exported_count}

## Contents

- **posts/**: Individual markdown files for each post
- **images/**: Backup of uploaded images (if added)

## File Naming Convention

Files are named as: `ID_Title.md`

## Importing Back

To import these posts back into the blog system, use the import utility.

---
Generated by Simple Blog Export System
"""
    
    with open(export_path / 'README.md', 'w', encoding='utf-8') as f:
        f.write(readme_content)
    
    return exported_count, str(export_path.absolute())

def export_to_json(output_dir='exports'):
    """Export all posts to a single JSON file"""
    import json
    
    export_path = Path(output_dir)
    export_path.mkdir(exist_ok=True)
    
    conn = get_db_connection()
    cursor = conn.cursor()
    
    cursor.execute('''
        SELECT 
            p.id, p.title, p.content, p.created_at, p.updated_at, p.is_published,
            c.name as category_name,
            GROUP_CONCAT(t.name, ',') as tags
        FROM posts p
        LEFT JOIN categories c ON p.category_id = c.id
        LEFT JOIN post_tags pt ON p.id = pt.post_id
        LEFT JOIN tags t ON pt.tag_id = t.id
        GROUP BY p.id
        ORDER BY p.created_at DESC
    ''')
    
    posts = [dict(row) for row in cursor.fetchall()]
    conn.close()
    
    # Create export data
    export_data = {
        'export_date': datetime.now().isoformat(),
        'total_posts': len(posts),
        'posts': posts
    }
    
    # Write to JSON file
    output_file = export_path / f'blog_export_{datetime.now().strftime("%Y%m%d_%H%M%S")}.json'
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(export_data, f, ensure_ascii=False, indent=2)
    
    return len(posts), str(output_file.absolute())

if __name__ == '__main__':
    print("Starting blog export...")
    
    # Export to Markdown
    print("\n1. Exporting to Markdown files...")
    count, path = export_all_posts_to_markdown()
    print(f"   ✓ Exported {count} posts to {path}/posts/")
    
    # Export to JSON
    print("\n2. Exporting to JSON...")
    count, path = export_to_json()
    print(f"   ✓ Exported {count} posts to {path}")
    
    print("\n✅ Export complete!")
