class DraftSyncManager{constructor(){this.autoSaveInterval=15000;this.autoSaveTimer=null;this.currentDraftId=null;this.lastSyncTime=null;this.deviceInfo=this.getDeviceInfo();this.postId=null;this.pendingRecoveryDraft=null;}
init(postId=null){this.postId=postId;this.loadLastSyncTime();this.observeContentChanges();this.checkForExistingDrafts();this.emitStatus('idle','未修改');}
observeContentChanges(){const titleInput=document.getElementById('title');const contentTextarea=document.getElementById('content');const categoryInput=document.getElementById('category_id');const tagsInput=document.getElementById('tags');const accessInput=document.getElementById('access_level');const debouncedSave=this.debounce(()=>{this.saveDraft();},this.autoSaveInterval);const markDirty=()=>this.emitStatus('dirty','有未保存修改');titleInput?.addEventListener('input',markDirty);titleInput?.addEventListener('input',debouncedSave);contentTextarea?.addEventListener('input',markDirty);contentTextarea?.addEventListener('input',debouncedSave);categoryInput?.addEventListener('change',markDirty);categoryInput?.addEventListener('change',debouncedSave);tagsInput?.addEventListener('input',markDirty);tagsInput?.addEventListener('input',debouncedSave);accessInput?.addEventListener('change',markDirty);accessInput?.addEventListener('change',debouncedSave);window.addEventListener('editor:content-change',markDirty);window.addEventListener('editor:content-change',debouncedSave);window.addEventListener('editor:images-updated',()=>{this.emitStatus('dirty','图片已更新，等待保存');});}
async saveDraft(){const saveStatus=document.getElementById('saveStatus');if(saveStatus){saveStatus.textContent='正在保存...';saveStatus.className='save-status saving';}
this.emitStatus('saving','正在同步到服务器...');try{const formData=this.getFormData();const response=await fetch('/api/drafts',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':this.getCsrfToken()},body:JSON.stringify({post_id:this.postId,device_info:this.deviceInfo,...formData})});const result=await response.json();if(result.success){this.currentDraftId=result.draft_id;this.lastSyncTime=result.updated_at;if(result.status==='conflict_detected'&&result.other_drafts?.length>0){this.showConflictDialog(result.other_drafts);}else{if(saveStatus){saveStatus.textContent=`已保存 ${this.getTimeAgo(result.updated_at)}`;saveStatus.className='save-status saved';}}
this.saveToLocalStorage(formData);localStorage.setItem(`last_sync_${this.postId||'new'}`,result.updated_at);this.emitStatus('saved',`服务器已保存 ${this.getTimeAgo(result.updated_at)}`,{serverTime:result.updated_at,localTime:new Date().toISOString()});}else{throw new Error(result.error);}}catch(error){console.error('草稿保存失败:',error);if(saveStatus){saveStatus.textContent='保存失败，已保存到本地';saveStatus.className='save-status error';}
const localTime=this.saveToLocalStorage(this.getFormData());this.emitStatus('offline','服务器保存失败，已备份到本地',{localTime});}}
async checkForExistingDrafts(){const localDraft=this.getFromLocalStorage();let serverDrafts=[];if(this.postId){try{const response=await fetch(`/api/drafts?post_id=${this.postId}`);const result=await response.json();if(result.success&&result.drafts?.length>0){serverDrafts=result.drafts;}}catch(error){console.error('检测草稿失败:',error);}}
const candidate=this.pickRecoveryCandidate(serverDrafts,localDraft);if(!candidate||this.isRecoveryDismissed(candidate)){return;}
this.pendingRecoveryDraft=candidate;this.showDraftRecoveryBanner(candidate);}
pickRecoveryCandidate(serverDrafts,localDraft){const candidates=[];const currentSnapshot=this.getComparableSnapshot(this.getFormData());if(Array.isArray(serverDrafts)){serverDrafts.forEach(draft=>{const candidate={...draft,source:'server',label:draft.device_info?`服务器草稿 · ${draft.device_info}`:'服务器草稿',timestamp:draft.updated_at};if(this.isMeaningfulDraft(candidate)&&!this.isSameAsCurrent(candidate,currentSnapshot)){candidates.push(candidate);}});}
if(localDraft){const candidate={...localDraft,source:'local',label:'本地草稿',timestamp:localDraft.saved_at};if(this.isMeaningfulDraft(candidate)&&!this.isSameAsCurrent(candidate,currentSnapshot)){candidates.push(candidate);}}
candidates.sort((a,b)=>new Date(b.timestamp||0)-new Date(a.timestamp||0));return candidates[0]||null;}
showDraftRecoveryBanner(candidate){const banner=document.getElementById('draftRecovery');if(!banner)return;const text=banner.querySelector('.recovery-text');if(text){text.textContent=`发现较新的${candidate.label}（${this.getTimeAgo(candidate.timestamp)}），需要时可以恢复。`;}
banner.style.display='block';}
hideDraftRecoveryBanner(){const banner=document.getElementById('draftRecovery');if(banner){banner.style.display='none';}}
showConflictDialog(otherDrafts){const modal=document.createElement('div');modal.className='draft-conflict-modal';const currentData=this.getFormData();modal.innerHTML=`<div class="modal-content"><div class="modal-header"><h2>⚠️ 检测到其他设备的草稿</h2></div><div class="modal-body"><div class="conflict-version"><h3>📱 ${otherDrafts[0].device_info}-${this.getTimeAgo(otherDrafts[0].updated_at)}</h3><div class="draft-preview">${otherDrafts[0].title}</div><button class="btn btn-primary"data-action="keep-other">使用此版本</button></div><hr><div class="conflict-version current"><h3>💻 ${this.deviceInfo}-刚刚</h3><div class="draft-preview">${currentData.title}</div><button class="btn btn-primary"data-action="keep-current">保留当前编辑</button></div><hr><button class="btn btn-secondary"data-action="merge">🔄 合并两个版本</button></div></div>`;modal.querySelectorAll('[data-action]').forEach(btn=>{btn.addEventListener('click',async()=>{await this.resolveConflict(otherDrafts[0].id,btn.dataset.action);modal.remove();});});document.body.appendChild(modal);}
async resolveConflict(otherDraftId,action){try{const response=await fetch('/api/drafts/resolve',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':this.getCsrfToken()},body:JSON.stringify({conflict_draft_id:otherDraftId,current_draft_id:this.currentDraftId,action:action})});const result=await response.json();if(result.success){this.showNotification(result.message,'success');if(action==='keep_other'){const draft=await this.loadServerDraft(otherDraftId);this.applyDraftData(draft);this.currentDraftId=draft.id;}}}catch(error){this.showNotification('解决冲突失败: '+error.message,'error');}}
getDeviceInfo(){const ua=navigator.userAgent;let browser='Unknown Browser';let os='Unknown OS';if(ua.includes('Chrome'))browser='Chrome';else if(ua.includes('Firefox'))browser='Firefox';else if(ua.includes('Safari'))browser='Safari';if(ua.includes('Windows'))os='Windows';else if(ua.includes('Mac'))os='macOS';else if(ua.includes('Linux'))os='Linux';else if(ua.includes('Android'))os='Android';else if(ua.includes('iOS'))os='iOS';return`${browser}on ${os}`;}
debounce(func,wait){let timeout;return function executedFunction(...args){const later=()=>{clearTimeout(timeout);func(...args);};clearTimeout(timeout);timeout=setTimeout(later,wait);};}
getTimeAgo(timestamp){const now=new Date();const past=new Date(timestamp);const diff=Math.floor((now-past)/1000);if(diff<60)return'刚刚';if(diff<3600)return`${Math.floor(diff/60)}分钟前`;if(diff<86400)return`${Math.floor(diff/3600)}小时前`;return`${Math.floor(diff/86400)}天前`;}
getFormData(){return{title:document.getElementById('title')?.value||'',content:document.getElementById('content')?.value||'',category_id:document.getElementById('category_id')?.value||null,tags:this.getTags(),access_level:document.getElementById('access_level')?.value||'public'};}
getTags(){const tagInput=document.getElementById('tags');if(tagInput){return tagInput.value.split(',').map(t=>t.trim()).filter(t=>t);}
return[];}
getCsrfToken(){return document.querySelector('meta[name="csrf_token"]')?.getAttribute('content');}
async loadServerDraft(draftId){const response=await fetch(`/api/drafts/${draftId}`);const result=await response.json();if(!result.success||!result.draft){throw new Error(result.error||'草稿不存在');}
return result.draft;}
applyDraftData(draft){if(!draft)return;const titleInput=document.getElementById('title');const contentTextarea=document.getElementById('content');const categorySelect=document.getElementById('category_id');const tagsInput=document.getElementById('tags');const accessInput=document.getElementById('access_level');const saveStatus=document.getElementById('saveStatus');if(titleInput)titleInput.value=draft.title||'';if(contentTextarea)contentTextarea.value=draft.content||'';if(window.quill){window.quill.root.innerHTML=draft.content||'';}
if(categorySelect){categorySelect.value=draft.category_id!=null?String(draft.category_id):'';}
if(tagsInput){const tags=Array.isArray(draft.tags)?draft.tags:[];tagsInput.value=tags.join(', ');}
if(accessInput&&draft.access_level){accessInput.value=draft.access_level;}
const localTime=this.saveToLocalStorage({title:titleInput?.value||'',content:contentTextarea?.value||'',category_id:categorySelect?.value||null,tags:this.getTags(),access_level:accessInput?.value||'public'});if(saveStatus){saveStatus.textContent='已恢复草稿';saveStatus.className='save-status saved';}
this.emitStatus('recovered','已恢复草稿',{localTime});window.dispatchEvent(new CustomEvent('editor:images-updated'));this.hideDraftRecoveryBanner();}
saveToLocalStorage(data){const savedAt=new Date().toISOString();localStorage.setItem(`draft_${this.postId||'new'}`,JSON.stringify({...data,saved_at:savedAt}));return savedAt;}
getFromLocalStorage(){const key=`draft_${this.postId||'new'}`;const data=localStorage.getItem(key);return data?JSON.parse(data):null;}
isMeaningfulDraft(draft){if(!draft)return false;const title=(draft.title||'').trim();const content=(draft.content||'').replace(/<[^>]+>/g,' ').trim();const tags=Array.isArray(draft.tags)?draft.tags:[];const categoryId=draft.category_id;const accessLevel=draft.access_level||'public';return Boolean(title||content||tags.length||categoryId||accessLevel!=='public');}
getComparableSnapshot(draft){const tags=Array.isArray(draft.tags)?draft.tags:[];const content=(draft.content||'').replace(/\s+/g,' ').trim();return JSON.stringify({title:(draft.title||'').trim(),content,category_id:draft.category_id||null,tags:tags.map(tag=>String(tag).trim()).filter(Boolean).sort(),access_level:draft.access_level||'public'});}
isSameAsCurrent(draft,currentSnapshot){return this.getComparableSnapshot(draft)===currentSnapshot;}
getRecoveryDismissKey(candidate){return`draft_recovery_dismissed_${this.postId||'new'}_${candidate.source}_${candidate.id||'local'}_${candidate.timestamp||'unknown'}`;}
isRecoveryDismissed(candidate){return Boolean(sessionStorage.getItem(this.getRecoveryDismissKey(candidate)));}
dismissRecoveryCandidate(candidate){sessionStorage.setItem(this.getRecoveryDismissKey(candidate),'1');this.hideDraftRecoveryBanner();}
async recoverPendingDraft(){const candidate=this.pendingRecoveryDraft;if(!candidate)return;try{if(candidate.source==='server'&&candidate.id){const draft=await this.loadServerDraft(candidate.id);this.applyDraftData(draft);this.currentDraftId=draft.id;this.showNotification('已恢复服务器草稿','success');}else{this.applyDraftData(candidate);this.showNotification('已恢复本地草稿','success');}}catch(error){this.showNotification('恢复草稿失败: '+error.message,'error');}}
discardPendingDraft(){const candidate=this.pendingRecoveryDraft;if(!candidate)return;this.dismissRecoveryCandidate(candidate);this.showNotification('本次已忽略这份草稿','info');}
clearDraftCache(){localStorage.removeItem(`draft_${this.postId||'new'}`);localStorage.removeItem(`last_sync_${this.postId||'new'}`);this.pendingRecoveryDraft=null;this.hideDraftRecoveryBanner();this.emitStatus('idle','未修改');}
cleanupServerDraft(){if(!this.currentDraftId)return;fetch(`/api/drafts/${this.currentDraftId}`,{method:'DELETE',keepalive:true,headers:{'X-CSRF-Token':this.getCsrfToken()}}).catch(()=>{});}
loadLastSyncTime(){const key=`last_sync_${this.postId||'new'}`;const time=localStorage.getItem(key);if(time){this.lastSyncTime=time;}}
showNotification(message,type='info'){if(typeof showNotification==='function'){showNotification(message,type);}else{console.log(`[${type}]${message}`);}}
emitStatus(status,message,meta={}){window.dispatchEvent(new CustomEvent('draftsync:status',{detail:{status,message,postId:this.postId,serverTime:meta.serverTime||this.lastSyncTime||null,localTime:meta.localTime||this.getFromLocalStorage()?.saved_at||null}}));}}
document.addEventListener('DOMContentLoaded',()=>{const pageType=document.body.dataset.page;if(pageType==='editor'||pageType==='admin'){const postIdElement=document.querySelector('[data-post-id]');const postId=postIdElement?.dataset.postId?parseInt(postIdElement.dataset.postId):null;window.draftSync=new DraftSyncManager();window.draftSync.init(postId);window.recoverDraft=()=>window.draftSync?.recoverPendingDraft();window.discardDraft=()=>window.draftSync?.discardPendingDraft();}});