(function(){'use strict';let images=[];let currentIndex=0;let currentShowingOriginal=false;function notify(message,type='success'){if(window.showAppToast){window.showAppToast(message,type);}}
function createLightbox(){if(document.querySelector('.lightbox-overlay')){return;}
const overlay=document.createElement('div');overlay.className='lightbox-overlay';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-label','图片预览');const container=document.createElement('div');container.className='lightbox-container';const img=document.createElement('img');img.className='lightbox-img';img.alt='灯箱图片';const closeBtn=document.createElement('button');closeBtn.className='lightbox-close';closeBtn.innerHTML='×';closeBtn.setAttribute('aria-label','关闭');const prevBtn=document.createElement('button');prevBtn.className='lightbox-nav lightbox-prev';prevBtn.innerHTML='‹';prevBtn.setAttribute('aria-label','上一张');const nextBtn=document.createElement('button');nextBtn.className='lightbox-nav lightbox-next';nextBtn.innerHTML='›';nextBtn.setAttribute('aria-label','下一张');const counter=document.createElement('div');counter.className='lightbox-counter';const caption=document.createElement('div');caption.className='lightbox-caption';const toolbar=document.createElement('div');toolbar.className='lightbox-toolbar';const originalBtn=document.createElement('button');originalBtn.className='lightbox-original-btn';originalBtn.innerHTML='📷 原图';originalBtn.setAttribute('aria-label','查看原图');const downloadBtn=document.createElement('button');downloadBtn.className='lightbox-download-btn';downloadBtn.innerHTML='⬇️ 下载';downloadBtn.setAttribute('aria-label','下载图片');toolbar.appendChild(originalBtn);toolbar.appendChild(downloadBtn);const loading=document.createElement('div');loading.className='lightbox-loading';loading.innerHTML='加载中...';container.appendChild(img);container.appendChild(loading);overlay.appendChild(container);overlay.appendChild(closeBtn);overlay.appendChild(prevBtn);overlay.appendChild(nextBtn);overlay.appendChild(counter);overlay.appendChild(caption);overlay.appendChild(toolbar);document.body.appendChild(overlay);bindLightboxEvents(overlay,img,closeBtn,prevBtn,nextBtn,originalBtn,downloadBtn);}
function bindLightboxEvents(overlay,img,closeBtn,prevBtn,nextBtn,originalBtn,downloadBtn){overlay.addEventListener('click',function(e){if(e.target===overlay){closeLightbox();}});closeBtn.addEventListener('click',closeLightbox);prevBtn.addEventListener('click',function(e){e.stopPropagation();showPreviousImage();});nextBtn.addEventListener('click',function(e){e.stopPropagation();showNextImage();});if(originalBtn){originalBtn.addEventListener('click',function(e){e.stopPropagation();toggleOriginalImage(img,originalBtn);});}
if(downloadBtn){downloadBtn.addEventListener('click',function(e){e.stopPropagation();downloadCurrentImage(img);});}
document.addEventListener('keydown',function(e){if(!overlay.classList.contains('active')){return;}
switch(e.key){case'Escape':closeLightbox();break;case'ArrowLeft':showPreviousImage();break;case'ArrowRight':showNextImage();break;}});img.addEventListener('load',function(){const loading=overlay.querySelector('.lightbox-loading');if(loading){loading.style.display='none';}
img.classList.add('animate');setTimeout(()=>img.classList.remove('animate'),300);});let touchStartX=0;let touchEndX=0;overlay.addEventListener('touchstart',function(e){touchStartX=e.changedTouches[0].screenX;},{passive:true});overlay.addEventListener('touchend',function(e){touchEndX=e.changedTouches[0].screenX;handleSwipe();},{passive:true});function handleSwipe(){const swipeThreshold=50;const diff=touchStartX-touchEndX;if(Math.abs(diff)>swipeThreshold){if(diff>0){showNextImage();}else{showPreviousImage();}}}}
function collectImages(){images=[];const postContent=document.querySelector('.post-content');if(!postContent){return;}
const imgElements=postContent.querySelectorAll('img');imgElements.forEach(function(img,index){if(img.naturalWidth&&img.naturalWidth<100){return;}
if(img.parentElement&&img.parentElement.tagName==='A'){return;}
if(!img.src||img.src.startsWith('data:')){return;}
const originalUrl=getOriginalImageUrl(img.src);images.push({src:img.src,originalUrl:originalUrl,alt:img.alt||`图片 ${index+1}`,element:img});img.dataset.lightboxIndex=images.length-1;if(originalUrl&&originalUrl!==img.src){img.dataset.originalUrl=originalUrl;}});}
function openLightbox(index){const overlay=document.querySelector('.lightbox-overlay');if(!overlay||!images.length){return;}
currentIndex=index;currentShowingOriginal=false;const imageData=images[currentIndex];const img=overlay.querySelector('.lightbox-img');const loading=overlay.querySelector('.lightbox-loading');const counter=overlay.querySelector('.lightbox-counter');const caption=overlay.querySelector('.lightbox-caption');const prevBtn=overlay.querySelector('.lightbox-prev');const nextBtn=overlay.querySelector('.lightbox-next');const originalBtn=overlay.querySelector('.lightbox-original-btn');if(loading){loading.style.display='block';}
img.src=imageData.src;img.alt=imageData.alt;updateCounter();if(caption){if(imageData.alt){caption.textContent=imageData.alt;caption.classList.add('show');}else{caption.classList.remove('show');}}
updateNavigationButtons(prevBtn,nextBtn);if(originalBtn){const hasOriginal=getOriginalImageUrl(imageData.src)!==imageData.src;if(hasOriginal){originalBtn.style.display='block';originalBtn.innerHTML='📷 原图';originalBtn.classList.remove('showing-original');}else{originalBtn.style.display='none';}}
overlay.classList.add('active');document.body.classList.add('lightbox-open');document.body.style.overflow='hidden';}
function closeLightbox(){const overlay=document.querySelector('.lightbox-overlay');if(!overlay){return;}
overlay.classList.remove('active');document.body.classList.remove('lightbox-open');document.body.style.overflow='';setTimeout(()=>{const img=overlay.querySelector('.lightbox-img');if(img){img.src='';}},300);}
function showPreviousImage(){if(currentIndex>0){openLightbox(currentIndex-1);}else{openLightbox(images.length-1);}}
function showNextImage(){if(currentIndex<images.length-1){openLightbox(currentIndex+1);}else{openLightbox(0);}}
function updateCounter(){const counter=document.querySelector('.lightbox-counter');if(counter&&images.length>1){counter.textContent=`${currentIndex+1}/${images.length}`;}else if(counter){counter.textContent='';}}
function updateNavigationButtons(prevBtn,nextBtn){if(images.length<=1){prevBtn.style.display='none';nextBtn.style.display='none';}else{prevBtn.style.display='flex';nextBtn.style.display='flex';}}
function getOriginalImageUrl(optimizedUrl){if(!optimizedUrl)return null;const optimizedMatch=optimizedUrl.match(/\/static\/uploads\/optimized\/([a-f0-9]+)_\w+\.webp/);if(optimizedMatch){const hash=optimizedMatch[1];const possibleOriginalUrls=[`/static/uploads/images/${hash}`,`/static/uploads/${hash}`,optimizedUrl.replace('/optimized/','/images/').replace(/_\w+\.webp$/,'')];return possibleOriginalUrls[0];}
return optimizedUrl;}
async function toggleOriginalImage(img,btn){const imageData=images[currentIndex];if(!imageData)return;const loading=document.querySelector('.lightbox-loading');if(loading){loading.style.display='block';}
if(!currentShowingOriginal){const urlMatch=imageData.src.match(/\/static\/uploads\/optimized\/([a-f0-9]+)_\w+\.webp/);if(urlMatch){const hash=urlMatch[1];try{const response=await fetch(`/api/image/original-url?hash=${hash}`);const data=await response.json();if(data.success&&data.exists&&data.original_url){const tempImg=new Image();tempImg.onload=function(){img.src=data.original_url;currentShowingOriginal=true;btn.innerHTML='🖼️ 优化版';btn.classList.add('showing-original');if(loading)loading.style.display='none';console.log(`已切换到原图:${data.original_url}`);};tempImg.onerror=function(){notify('原图存在但无法加载，请先保存当前优化图','error');if(loading)loading.style.display='none';};tempImg.src=data.original_url;}else{notify('原图文件不存在，请使用当前优化图或重新上传','error');if(loading)loading.style.display='none';}}catch(error){console.error('获取原图URL失败:',error);notify('无法获取原图信息，请稍后再试','error');if(loading)loading.style.display='none';}}else{notify('无法识别图片格式，请先下载当前图片','error');if(loading)loading.style.display='none';}}else{img.src=imageData.src;currentShowingOriginal=false;btn.innerHTML='📷 原图';btn.classList.remove('showing-original');if(loading)loading.style.display='none';}}
function downloadCurrentImage(img){if(!img||!img.src)return;let filename=`image_${currentIndex+1}_${Date.now()}`;const urlMatch=img.src.match(/\.([a-z]+)(?:\?|$)/);if(urlMatch){const ext=urlMatch[1];filename+=`.${ext}`;}else{filename+='.jpg';}
fetch(img.src).then(response=>response.blob()).then(blob=>{const blobUrl=window.URL.createObjectURL(blob);const link=document.createElement('a');link.href=blobUrl;link.download=filename;document.body.appendChild(link);link.click();document.body.removeChild(link);window.URL.revokeObjectURL(blobUrl);console.log(`下载图片:${img.src}->${filename}`);}).catch(error=>{console.error('下载失败:',error);const link=document.createElement('a');link.href=img.src;link.download=filename;link.target='_blank';document.body.appendChild(link);link.click();document.body.removeChild(link);notify('下载已开始，如打开新标签页请右键保存图片');});}
function addImageClickHandlers(){const postContent=document.querySelector('.post-content');if(!postContent){return;}
postContent.addEventListener('click',function(e){const img=e.target.closest('img');if(!img){return;}
const index=parseInt(img.dataset.lightboxIndex);if(!isNaN(index)){e.preventDefault();openLightbox(index);}});}
function init(){if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',initialize);}else{initialize();}}
function initialize(){createLightbox();collectImages();addImageClickHandlers();console.log(`图片灯箱已初始化，找到 ${images.length}张图片`);}
init();})();