(function(){'use strict';let startY=0;let isPulling=false;let isRefreshing=false;const threshold=80;document.addEventListener('DOMContentLoaded',function(){if(window.innerWidth<=768){initPullRefresh();}});function initPullRefresh(){createRefreshIndicator();document.addEventListener('touchstart',handleTouchStart,{passive:true});document.addEventListener('touchmove',handleTouchMove,{passive:false});document.addEventListener('touchend',handleTouchEnd,{passive:true});}
function createRefreshIndicator(){const indicator=document.createElement('div');indicator.id='pullRefreshIndicator';indicator.className='pull-refresh-indicator';indicator.innerHTML='<div class="spinner"></div>';document.body.appendChild(indicator);}
function handleTouchStart(e){if(isRefreshing)return;if(window.scrollY>5)return;startY=e.touches[0].pageY;isPulling=true;}
function handleTouchMove(e){if(!isPulling||isRefreshing)return;const currentY=e.touches[0].pageY;const diff=currentY-startY;if(diff<=0)return;e.preventDefault();const pullDistance=Math.min(diff*0.5,threshold*2);updateRefreshIndicator(pullDistance);}
function handleTouchEnd(e){if(!isPulling)return;isPulling=false;const indicator=document.getElementById('pullRefreshIndicator');if(!indicator)return;const currentTop=parseInt(indicator.style.top)||-60;if(currentTop>=10){startRefresh();}else{resetRefreshIndicator();}}
function updateRefreshIndicator(distance){const indicator=document.getElementById('pullRefreshIndicator');if(!indicator)return;const top=Math.min(-60+distance,20);indicator.style.top=top+'px';const spinner=indicator.querySelector('.spinner');if(spinner){const rotation=(distance/threshold)*180;spinner.style.transform=`rotate(${rotation}deg)`;spinner.style.animation='none';}}
function resetRefreshIndicator(){const indicator=document.getElementById('pullRefreshIndicator');if(!indicator)return;indicator.style.top='-60px';indicator.classList.remove('refreshing');const spinner=indicator.querySelector('.spinner');if(spinner){spinner.style.transform='';spinner.style.animation='';}}
async function startRefresh(){if(isRefreshing)return;isRefreshing=true;const indicator=document.getElementById('pullRefreshIndicator');if(indicator){indicator.classList.add('refreshing');const spinner=indicator.querySelector('.spinner');if(spinner){spinner.style.animation='spin 0.8s linear infinite';}}
try{await performRefresh();}finally{setTimeout(()=>{isRefreshing=false;resetRefreshIndicator();},500);}}
async function performRefresh(){if(window.InfiniteScroll&&typeof window.InfiniteScroll.refresh==='function'){const refreshed=await window.InfiniteScroll.refresh();if(refreshed){return;}}
window.location.reload();}
window.PullRefresh={trigger:function(){startRefresh();}};})();