class ShortcutHandler{constructor(){this.shortcuts=new Map();this.init();}
init(){document.addEventListener('keydown',this.handleKeyDown.bind(this));}
register(key,callback,description=''){this.shortcuts.set(key.toLowerCase(),{callback,description});}
handleKeyDown(e){const key=this.getKeyString(e);const shortcut=this.shortcuts.get(key);if(shortcut){e.preventDefault();e.stopPropagation();shortcut.callback(e);}}
getKeyString(e){const parts=[];if(e.ctrlKey&&!e.metaKey)parts.push('ctrl');if(e.metaKey&&!e.ctrlKey)parts.push('cmd');if(e.shiftKey)parts.push('shift');if(e.altKey)parts.push('alt');let key=e.key.toLowerCase();const keyMap={' ':'space','escape':'esc','arrowup':'up','arrowdown':'down','arrowleft':'left','arrowright':'right'};if(keyMap[key]){key=keyMap[key];}
parts.push(key);return parts.join('+');}
getShortcuts(){return Array.from(this.shortcuts.entries()).map(([key,value])=>({key:this.formatKey(key),description:value.description}));}
formatKey(key){return key.replace('ctrl','Ctrl').replace('cmd','Cmd⌘').replace('shift','Shift').replace('alt','Alt').replace('esc','Esc').split('+').join('+');}}
const shortcutHandler=new ShortcutHandler();document.addEventListener('DOMContentLoaded',()=>{const currentPage=document.body.dataset.page||'home';shortcutHandler.register('ctrl+k',()=>{const searchInput=document.querySelector('.search-input-nav, input[name="q"], input[placeholder*="搜索"]');if(searchInput){searchInput.focus();searchInput.select();}},'打开搜索');shortcutHandler.register('ctrl+/',()=>{showShortcutHelp();},'显示快捷键帮助');shortcutHandler.register('ctrl+n',()=>{const newPostBtn=document.querySelector('a[href*="/admin/new"], a[href*="/new"]');if(newPostBtn){window.location.href=newPostBtn.href;}},'新建文章');shortcutHandler.register('ctrl+shift+n',()=>{const quickNoteBtn=document.querySelector('a[href*="quick_note"]');if(quickNoteBtn){window.location.href=quickNoteBtn.href;}},'快速记事');shortcutHandler.register('esc',()=>{const modals=document.querySelectorAll('.shortcut-help-modal, .modal, [role="dialog"]');modals.forEach(modal=>modal.remove());},'关闭弹窗');switch(currentPage){case'editor':registerEditorShortcuts();break;case'quick_note':registerQuickNoteShortcuts();break;case'admin':registerAdminShortcuts();break;case'timeline':registerTimelineShortcuts();break;}});function registerEditorShortcuts(){shortcutHandler.register('ctrl+s',()=>{const saveBtn=document.querySelector('#saveBtn, button[type="submit"]');if(saveBtn){saveBtn.click();}},'保存文章');shortcutHandler.register('ctrl+shift+s',()=>{saveDraft();},'保存草稿');shortcutHandler.register('ctrl+p',()=>{togglePreview();},'切换预览');shortcutHandler.register('ctrl+shift+t',()=>{if(typeof generateAITags==='function'){generateAITags();}},'AI生成标签');shortcutHandler.register('esc',async(event)=>{event.stopPropagation();const confirmed=window.showAppConfirm?await window.showAppConfirm('确定要离开编辑器吗？未保存的内容将丢失。'):true;if(confirmed){window.history.back();}},'关闭编辑器');const quillEditor=document.querySelector('.ql-editor');if(quillEditor){shortcutHandler.register('ctrl+d',()=>{const date=new Date().toLocaleDateString('zh-CN');insertAtCursor(date);},'插入日期');shortcutHandler.register('ctrl+b',()=>{quillEditor.focus();document.execCommand('bold');},'加粗');shortcutHandler.register('ctrl+i',()=>{quillEditor.focus();document.execCommand('italic');},'斜体');shortcutHandler.register('ctrl+shift+k',()=>{const quill=window.quill;if(quill){const range=quill.getSelection();if(range){quill.insertText(range.index,range.length,'`','user');}}},'插入代码');shortcutHandler.register('ctrl+alt+l',()=>{const quill=window.quill;if(quill){const range=quill.getSelection();if(range){quill.formatLine(range.index,1,'list','bullet');}}},'无序列表');shortcutHandler.register('ctrl+alt+o',()=>{const quill=window.quill;if(quill){const range=quill.getSelection();if(range){quill.formatLine(range.index,1,'list','ordered');}}},'有序列表');}}
function registerQuickNoteShortcuts(){shortcutHandler.register('ctrl+s',()=>{const form=document.getElementById('quick-note-form');if(form){form.dispatchEvent(new Event('submit'));}},'快速保存');shortcutHandler.register('ctrl+shift+d',()=>{const clearBtn=document.getElementById('clear-btn');if(clearBtn){clearBtn.click();}},'清空内容');shortcutHandler.register('ctrl+n',()=>{document.getElementById('title').value='';document.getElementById('content').value='';document.getElementById('content').focus();},'新建笔记');}
function registerAdminShortcuts(){shortcutHandler.register('ctrl+n',()=>{const newPostBtn=document.querySelector('a[href*="/new"]');if(newPostBtn){window.location.href=newPostBtn.href;}},'新建文章');shortcutHandler.register('ctrl+shift+n',()=>{const quickNoteBtn=document.querySelector('a[href*="quick_note"]');if(quickNoteBtn){window.location.href=quickNoteBtn.href;}},'打开快速记事');shortcutHandler.register('ctrl+r',()=>{if(window.InfiniteScroll&&typeof window.InfiniteScroll.refresh==='function'){window.InfiniteScroll.refresh().then(refreshed=>{if(!refreshed){location.reload();}});return;}
location.reload();},'刷新页面');}
function registerTimelineShortcuts(){shortcutHandler.register('ctrl+n',()=>{const quickNoteBtn=document.querySelector('a[href*="quick_note"]');if(quickNoteBtn){window.location.href=quickNoteBtn.href;}},'新建笔记');shortcutHandler.register('ctrl+f',()=>{const filterInput=document.querySelector('input[placeholder*="筛选"]');if(filterInput){filterInput.focus();}},'筛选内容');shortcutHandler.register('ctrl+r',()=>{if(window.InfiniteScroll&&typeof window.InfiniteScroll.refresh==='function'){window.InfiniteScroll.refresh().then(refreshed=>{if(!refreshed){location.reload();}});return;}
location.reload();},'刷新时间线');}
function saveDraft(){const form=document.getElementById('editorForm');if(!form)return;const formData=new FormData(form);formData.set('is_published','false');fetch(form.action,{method:'POST',body:formData,credentials:'same-origin'}).then(response=>response.json()).then(data=>{if(data.success){showNotification('草稿已保存','success');}else{showNotification('保存失败: '+data.error,'error');}}).catch(error=>{showNotification('保存失败: '+error.message,'error');});}
function togglePreview(){const previewPane=document.querySelector('.preview-pane');if(previewPane){previewPane.classList.toggle('active');}else{createPreviewPane();}}
function createPreviewPane(){const editorContainer=document.querySelector('.admin-editor');if(!editorContainer)return;if(document.querySelector('.preview-pane'))return;const editorPane=editorContainer.querySelector('.editor-form');const previewPane=document.createElement('div');previewPane.className='preview-pane';previewPane.innerHTML=`<div class="preview-header"><h3>预览</h3><button class="close-preview"onclick="togglePreview()">×</button></div><div class="preview-content"id="previewContent"></div>`;editorContainer.insertBefore(previewPane,editorPane);updatePreview();const titleInput=document.getElementById('title');const contentTextarea=document.getElementById('content');if(titleInput){titleInput.addEventListener('input',debounce(updatePreview,300));}
if(contentTextarea){contentTextarea.addEventListener('input',debounce(updatePreview,300));}}
function updatePreview(){const title=document.getElementById('title').value;const content=document.getElementById('content').value;const previewContent=document.getElementById('previewContent');if(previewContent){const html=markdownToHTML(content);previewContent.innerHTML=`<h1>${title||'（无标题）'}</h1>${html}`;}}
function markdownToHTML(markdown){if(!markdown)return'';return markdown.replace(/^# (.+)$/gm,'<h1>$1</h1>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^#### (.+)$/gm,'<h4>$1</h4>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\*(.+?)\*/g,'<em>$1</em>').replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2">$1</a>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/```([\s\S]*?)```/g,'<pre><code>$1</code></pre>').replace(/\n\n/g,'</p><p>').replace(/^/,'<p>').replace(/$/,'</p>');}
function insertAtCursor(text){const textarea=document.getElementById('content');if(!textarea)return;const start=textarea.selectionStart;const end=textarea.selectionEnd;const value=textarea.value;textarea.value=value.substring(0,start)+text+value.substring(end);textarea.selectionStart=textarea.selectionEnd=start+text.length;textarea.focus();}
function showShortcutHelp(){const shortcuts=shortcutHandler.getShortcuts();const modal=document.createElement('div');modal.className='shortcut-help-modal';modal.innerHTML=`<div class="modal-content"><div class="modal-header"><h2>⌨️ 键盘快捷键</h2><button class="close-modal"onclick="this.closest('.shortcut-help-modal').remove()">×</button></div><div class="modal-body"><table class="shortcut-table"><thead><tr><th>快捷键</th><th>说明</th></tr></thead><tbody>${shortcuts.map(s=>`<tr><td><code>${s.key}</code></td><td>${s.description}</td></tr>`).join('')}</tbody></table><div class="shortcut-note"><p><strong>提示：</strong></p><ul><li><code>Ctrl</code>在 Windows/Linux 上使用</li><li><code>Cmd⌘</code>在 macOS 上使用</li><li>按<code>Ctrl+/</code>可随时查看此帮助</li></ul></div></div></div>`;document.body.appendChild(modal);modal.addEventListener('click',(e)=>{if(e.target===modal){modal.remove();}});}
function debounce(func,wait){let timeout;return function executedFunction(...args){const later=()=>{clearTimeout(timeout);func(...args);};clearTimeout(timeout);timeout=setTimeout(later,wait);};}
function showNotification(message,type='info'){const notification=document.createElement('div');notification.className=`notification notification-${type}`;notification.textContent=message;notification.style.cssText=`position:fixed;top:20px;right:20px;padding:12px 20px;background:${type==='success'?'#d4edda':type==='error'?'#f8d7da':'#d1ecf1'};color:${type==='success'?'#155724':type==='error'?'#721c24':'#0c5460'};border-radius:6px;box-shadow:0 4px 12px rgba(0,0,0,0.15);z-index:10000;animation:slideIn 0.3s ease-out;`;document.body.appendChild(notification);setTimeout(()=>{notification.style.animation='slideOut 0.3s ease-out';setTimeout(()=>notification.remove(),300);},3000);}
const style=document.createElement('style');style.textContent=`@keyframes slideIn{from{transform:translateX(100%);opacity:0;}
to{transform:translateX(0);opacity:1;}}@keyframes slideOut{from{transform:translateX(0);opacity:1;}
to{transform:translateX(100%);opacity:0;}}.shortcut-help-modal{position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.5);display:flex;align-items:center;justify-content:center;z-index:9999;}.shortcut-help-modal.modal-content{background:var(--card-bg,#fff);border-radius:12px;max-width:600px;width:90%;max-height:80vh;overflow:hidden;box-shadow:0 20px 60px rgba(0,0,0,0.3);}.shortcut-help-modal.modal-header{display:flex;justify-content:space-between;align-items:center;padding:20px;border-bottom:1px solid var(--border-color,#e5e7eb);}.shortcut-help-modal.modal-header h2{margin:0;font-size:1.5rem;}.shortcut-help-modal.close-modal{background:none;border:none;font-size:1.5rem;cursor:pointer;padding:0;width:32px;height:32px;display:flex;align-items:center;justify-content:center;}.shortcut-help-modal.modal-body{padding:20px;overflow-y:auto;max-height:calc(80vh-80px);}.shortcut-table{width:100%;border-collapse:collapse;}.shortcut-table th,.shortcut-table td{padding:12px;text-align:left;border-bottom:1px solid var(--border-color,#e5e7eb);}.shortcut-table th{background:var(--code-bg,#f9fafb);font-weight:600;}.shortcut-table code{background:var(--code-bg,#f3f4f6);padding:4px 8px;border-radius:4px;font-family:monospace;font-size:0.9em;}.shortcut-note{margin-top:20px;padding:15px;background:var(--code-bg,#f9fafb);border-radius:8px;}.shortcut-note ul{margin:10px 0 0 0;padding-left:20px;}.shortcut-note li{margin:5px 0;}.preview-pane{flex:1;background:var(--card-bg,#fff);border-left:1px solid var(--border-color,#e5e7eb);display:none;}.preview-pane.active{display:block;}.preview-header{display:flex;justify-content:space-between;align-items:center;padding:15px 20px;border-bottom:1px solid var(--border-color,#e5e7eb);}.preview-header h3{margin:0;font-size:1.1rem;}.preview-header.close-preview{background:none;border:none;font-size:1.5rem;cursor:pointer;padding:0;}.preview-content{padding:20px;max-height:calc(100vh-200px);overflow-y:auto;}.preview-content h1,.preview-content h2,.preview-content h3,.preview-content h4{margin-top:1.5em;margin-bottom:0.5em;}.preview-content p{line-height:1.6;margin-bottom:1em;}.preview-content code{background:var(--code-bg,#f3f4f6);padding:2px 6px;border-radius:3px;}.preview-content pre{background:var(--code-bg,#f3f4f6);padding:15px;border-radius:6px;overflow-x:auto;}.preview-content a{color:var(--primary-color,#007bff);text-decoration:none;}.preview-content a:hover{text-decoration:underline;}`;document.head.appendChild(style);class ShortcutHint{constructor(){this.hintElement=null;this.autoFadeTimer=null;this.init();}
init(){if(window.location.search.includes('debug=1')){console.log('=== 快捷键调试信息 ===');console.log('用户代理:',navigator.userAgent);console.log('屏幕宽度:',window.innerWidth);console.log('触摸支持:','ontouchstart'in window);console.log('最大触摸点:',navigator.maxTouchPoints);console.log('检测为移动设备:',this.isMobileDevice());console.log('======================');}
if(this.isMobileDevice()){console.log('✓ 检测到移动设备，已隐藏快捷键提示');return;}
if(sessionStorage.getItem('shortcutHintDismissed')==='true'){return;}
this.createHintElement();this.show();}
isMobileDevice(){const userAgent=navigator.userAgent||navigator.vendor||window.opera;if(/iPhone/.test(userAgent)){return true;}
if(/iPad/.test(userAgent)||(/Macintosh/.test(userAgent)&&navigator.maxTouchPoints>1)){return true;}
const mobileRegex=/Android|webOS|iPod|BlackBerry|IEMobile|Opera Mini/i;if(mobileRegex.test(userAgent)){return true;}
if(window.innerWidth&&window.innerWidth<768){return true;}
const hasTouchScreen=('ontouchstart'in window||navigator.maxTouchPoints>0||navigator.msMaxTouchPoints>0);if(hasTouchScreen&&window.innerWidth<1024){return true;}
return false;}
createHintElement(){const hint=document.createElement('div');hint.id='shortcutHint';hint.className='shortcut-hint';hint.innerHTML=`<div class="hint-header"><span>⌨️ 快捷键提示</span><button class="hint-close"onclick="window.shortcutHint.hide()">×</button></div><div class="hint-body">${this.getCurrentPageShortcuts()}</div>`;document.body.appendChild(hint);this.hintElement=hint;}
getCurrentPageShortcuts(){const pageType=document.body.dataset.page||'home';const shortcuts={'home':[{keys:['Ctrl','K'],desc:'快速搜索'},{keys:['Ctrl','N'],desc:'新建文章'},{keys:['Ctrl','/'],desc:'查看更多'}],'editor':[{keys:['Ctrl','S'],desc:'保存文章'},{keys:['Ctrl','P'],desc:'切换预览'},{keys:['ESC'],desc:'关闭编辑器'}],'admin':[{keys:['Ctrl','N'],desc:'新建文章'},{keys:['Ctrl','K'],desc:'快速搜索'},{keys:['Ctrl','/'],desc:'查看更多'}]};const pageShortcuts=shortcuts[pageType]||shortcuts['home'];return pageShortcuts.map(s=>`<div class="hint-item">${s.keys.map(k=>`<kbd>${k}</kbd>`).join(' + ')}<span>${s.desc}</span></div>`).join('');}
show(){if(!this.hintElement)return;this.hintElement.style.display='block';this.autoFadeTimer=setTimeout(()=>{this.hide();},3000);}
hide(){if(!this.hintElement)return;if(this.autoFadeTimer){clearTimeout(this.autoFadeTimer);this.autoFadeTimer=null;}
this.hintElement.style.opacity='0';setTimeout(()=>{if(this.hintElement){this.hintElement.style.display='none';}},300);sessionStorage.setItem('shortcutHintDismissed','true');}}
document.addEventListener('DOMContentLoaded',()=>{window.shortcutHint=new ShortcutHint();});